<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ListeningQuestion;
use App\Services\TextToSpeechService;

class ListeningQuestionsSeeder extends Seeder
{
    public function run(TextToSpeechService $ttsService)
    {
        $questions = [
            // 添加問題數據
            // 簡單
    [
        'question' => 'What time does the meeting start?',
        'option_a' => '10:30 AM',
        'option_b' => '9:00 AM',
        'option_c' => '12:00 PM',
        'option_d' => '2:00 PM',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'time',
    ],
    [
        'question' => 'Where is the nearest bus stop?',
        'option_a' => 'Around the corner',
        'option_b' => 'Across the street',
        'option_c' => 'At the next intersection',
        'option_d' => 'In front of the building',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'location',
    ],

    // 中等
    [
        'question' => 'What are the store hours?',
        'option_a' => '9 AM to 5 PM',
        'option_b' => '10 AM to 6 PM',
        'option_c' => '8 AM to 4 PM',
        'option_d' => '11 AM to 7 PM',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],
    [
        'question' => 'What is the main topic of the meeting?',
        'option_a' => 'Budget review',
        'option_b' => 'Project update',
        'option_c' => 'Team building',
        'option_d' => 'Marketing strategy',
        'correct_answer' => 'optionb',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],

    // 困難
    [
        'question' => 'What should you do if you are running late?',
        'option_a' => 'Call your supervisor',
        'option_b' => 'Send an email',
        'option_c' => 'Arrive as planned',
        'option_d' => 'Skip the meeting',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'hard',
        'category' => 'conversation',
    ],
    [
        'question' => 'How much time do you have to complete the project?',
        'option_a' => 'One week',
        'option_b' => 'Two weeks',
        'option_c' => 'Three weeks',
        'option_d' => 'One month',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'hard',
        'category' => 'work',
    ],

    // 超難
    [
        'question' => 'What was the reason for the product recall?',
        'option_a' => 'Defective parts',
        'option_b' => 'Safety concerns',
        'option_c' => 'Quality assurance',
        'option_d' => 'Marketing strategy',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'What is the expected outcome of the meeting?',
        'option_a' => 'Increase sales',
        'option_b' => 'Launch new product',
        'option_c' => 'Improve customer service',
        'option_d' => 'Reduce costs',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'How should you respond to customer complaints?',
        'option_a' => 'Ignore them',
        'option_b' => 'Address them promptly',
        'option_c' => 'Pass them to a manager',
        'option_d' => 'Make excuses',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'very hard',
        'category' => 'customer service',
    ],
    [
        'question' => 'What challenges might the team face with the new project?',
        'option_a' => 'Lack of resources',
        'option_b' => 'Time constraints',
        'option_c' => 'Team disagreements',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'teamwork',
    ],




    // 簡單
    [
        'question' => 'What is the weather like today?',
        'option_a' => 'Sunny',
        'option_b' => 'Rainy',
        'option_c' => 'Cloudy',
        'option_d' => 'Windy',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'weather',
    ],
    [
        'question' => 'Where is the nearest coffee shop?',
        'option_a' => 'Next to the bank',
        'option_b' => 'Across the street',
        'option_c' => 'Inside the mall',
        'option_d' => 'In the park',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'location',
    ],
    [
        'question' => 'What time does the store open?',
        'option_a' => '8 AM',
        'option_b' => '9 AM',
        'option_c' => '10 AM',
        'option_d' => '11 AM',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'business',
    ],
    [
        'question' => 'How often do you go to the gym?',
        'option_a' => 'Every day',
        'option_b' => 'Once a week',
        'option_c' => 'Twice a month',
        'option_d' => 'Never',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'health',
    ],
    [
        'question' => 'What is your favorite color?',
        'option_a' => 'Red',
        'option_b' => 'Blue',
        'option_c' => 'Green',
        'option_d' => 'Yellow',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],

    // 中等
    [
        'question' => 'What are the benefits of a healthy diet?',
        'option_a' => 'Improved energy',
        'option_b' => 'Better sleep',
        'option_c' => 'Weight loss',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'health',
    ],
    [
        'question' => 'What is the purpose of the meeting?',
        'option_a' => 'To discuss project updates',
        'option_b' => 'To review financial reports',
        'option_c' => 'To plan a company event',
        'option_d' => 'To conduct employee training',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],
    [
        'question' => 'How long will the project take?',
        'option_a' => 'One month',
        'option_b' => 'Two months',
        'option_c' => 'Three months',
        'option_d' => 'Four months',
        'correct_answer' => 'optionc',
        'difficulty_level' => 'medium',
        'category' => 'work',
    ],
    [
        'question' => 'What should you do if you encounter a problem?',
        'option_a' => 'Ask for help',
        'option_b' => 'Ignore it',
        'option_c' => 'Try to solve it yourself',
        'option_d' => 'Report it to your manager',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'medium',
        'category' => 'problem-solving',
    ],
    [
        'question' => 'What is the deadline for the report?',
        'option_a' => 'Next Monday',
        'option_b' => 'Tomorrow',
        'option_c' => 'At the end of the month',
        'option_d' => 'Next week',
        'correct_answer' => 'optionc',
        'difficulty_level' => 'medium',
        'category' => 'work',
    ],

    // 困難
    [
        'question' => 'What are the key factors for success in business?',
        'option_a' => 'Planning and execution',
        'option_b' => 'Innovation and creativity',
        'option_c' => 'Customer satisfaction',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'business',
    ],
    [
        'question' => 'What is the main challenge of the new project?',
        'option_a' => 'Limited resources',
        'option_b' => 'Tight deadlines',
        'option_c' => 'Team collaboration',
        'option_d' => 'Market competition',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'hard',
        'category' => 'project management',
    ],
    [
        'question' => 'How can we improve customer service?',
        'option_a' => 'More training for staff',
        'option_b' => 'Faster response times',
        'option_c' => 'Better communication',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'customer service',
    ],
    [
        'question' => 'What are the advantages of working in a team?',
        'option_a' => 'Diverse perspectives',
        'option_b' => 'Shared responsibilities',
        'option_c' => 'Increased creativity',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'teamwork',
    ],

    // 超難
    [
        'question' => 'What is the significance of market research?',
        'option_a' => 'Understanding consumer needs',
        'option_b' => 'Identifying trends',
        'option_c' => 'Enhancing product development',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'How should you handle a difficult customer?',
        'option_a' => 'Stay calm and listen',
        'option_b' => 'Argue with them',
        'option_c' => 'Transfer them to a manager',
        'option_d' => 'Ignore their complaints',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'very hard',
        'category' => 'customer service',
    ],
    [
        'question' => 'What strategies can be used for effective communication?',
        'option_a' => 'Active listening',
        'option_b' => 'Clear and concise messaging',
        'option_c' => 'Non-verbal cues',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'communication',
    ],
    [
        'question' => 'How can technology enhance productivity in the workplace?',
        'option_a' => 'Automation of tasks',
        'option_b' => 'Improved communication tools',
        'option_c' => 'Data analysis',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],
    [
        'question' => 'What factors contribute to a successful marketing campaign?',
        'option_a' => 'Target audience research',
        'option_b' => 'Effective messaging',
        'option_c' => 'Multiple channels of promotion',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'marketing',
    ],







    // 簡單
    [
        'question' => 'What is your favorite hobby?',
        'option_a' => 'Reading',
        'option_b' => 'Traveling',
        'option_c' => 'Cooking',
        'option_d' => 'Sports',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],
    [
        'question' => 'What do you like to drink in the morning?',
        'option_a' => 'Tea',
        'option_b' => 'Coffee',
        'option_c' => 'Juice',
        'option_d' => 'Water',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'food',
    ],
    [
        'question' => 'What is the capital city of France?',
        'option_a' => 'Berlin',
        'option_b' => 'Madrid',
        'option_c' => 'Paris',
        'option_d' => 'Rome',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'geography',
    ],
    [
        'question' => 'What kind of music do you like?',
        'option_a' => 'Pop',
        'option_b' => 'Rock',
        'option_c' => 'Jazz',
        'option_d' => 'Classical',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'music',
    ],
    [
        'question' => 'What do you do on weekends?',
        'option_a' => 'Relax',
        'option_b' => 'Work',
        'option_c' => 'Shop',
        'option_d' => 'Visit friends',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'easy',
        'category' => 'lifestyle',
    ],

    // 中等
    [
        'question' => 'What is the main purpose of a business plan?',
        'option_a' => 'To secure funding',
        'option_b' => 'To outline goals',
        'option_c' => 'To analyze competition',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],
    [
        'question' => 'How can you improve your language skills?',
        'option_a' => 'Practice regularly',
        'option_b' => 'Watch movies',
        'option_c' => 'Read books',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'education',
    ],
    [
        'question' => 'What factors should be considered when planning a trip?',
        'option_a' => 'Budget',
        'option_b' => 'Destination',
        'option_c' => 'Duration',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'travel',
    ],
    [
        'question' => 'What are the benefits of reading regularly?',
        'option_a' => 'Improved vocabulary',
        'option_b' => 'Better focus',
        'option_c' => 'Enhanced knowledge',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'personal development',
    ],
    [
        'question' => 'What is the purpose of a resume?',
        'option_a' => 'To get a job',
        'option_b' => 'To showcase skills',
        'option_c' => 'To outline experience',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'career',
    ],

    // 困難
    [
        'question' => 'What are the challenges of remote work?',
        'option_a' => 'Isolation',
        'option_b' => 'Distractions at home',
        'option_c' => 'Communication issues',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'work',
    ],
    [
        'question' => 'How can businesses benefit from social media?',
        'option_a' => 'Increased brand awareness',
        'option_b' => 'Better customer engagement',
        'option_c' => 'Targeted advertising',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'marketing',
    ],
    [
        'question' => 'What is the role of a project manager?',
        'option_a' => 'Overseeing project execution',
        'option_b' => 'Managing the team',
        'option_c' => 'Communicating with stakeholders',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'management',
    ],
    [
        'question' => 'What strategies can be used to handle stress?',
        'option_a' => 'Exercise',
        'option_b' => 'Meditation',
        'option_c' => 'Time management',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'wellness',
    ],

    // 超難
    [
        'question' => 'What are the implications of climate change?',
        'option_a' => 'Rising sea levels',
        'option_b' => 'Extreme weather events',
        'option_c' => 'Biodiversity loss',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'environment',
    ],
    [
        'question' => 'How can organizations promote diversity and inclusion?',
        'option_a' => 'Training programs',
        'option_b' => 'Diverse hiring practices',
        'option_c' => 'Inclusive policies',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'HR',
    ],
    [
        'question' => 'What is the significance of data security?',
        'option_a' => 'Protecting sensitive information',
        'option_b' => 'Maintaining customer trust',
        'option_c' => 'Compliance with regulations',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'IT',
    ],
    [
        'question' => 'How do economic factors affect consumer behavior?',
        'option_a' => 'Income levels',
        'option_b' => 'Employment rates',
        'option_c' => 'Inflation',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'economics',
    ],
    [
        'question' => 'What are the benefits of lifelong learning?',
        'option_a' => 'Career advancement',
        'option_b' => 'Personal growth',
        'option_c' => 'Adaptability to change',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'education',
    ],





     // 簡單
     [
        'question' => 'What is your name?',
        'option_a' => 'John',
        'option_b' => 'Jane',
        'option_c' => 'Mike',
        'option_d' => 'Sara',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],
    [
        'question' => 'How many days are there in a week?',
        'option_a' => '5',
        'option_b' => '6',
        'option_c' => '7',
        'option_d' => '8',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'general knowledge',
    ],
    [
        'question' => 'What is the capital of France?',
        'option_a' => 'London',
        'option_b' => 'Berlin',
        'option_c' => 'Paris',
        'option_d' => 'Madrid',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'geography',
    ],
    [
        'question' => 'What color is the sky?',
        'option_a' => 'Blue',
        'option_b' => 'Green',
        'option_c' => 'Red',
        'option_d' => 'Yellow',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'nature',
    ],
    [
        'question' => 'What is 2 + 2?',
        'option_a' => '3',
        'option_b' => '4',
        'option_c' => '5',
        'option_d' => '6',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'math',
    ],

    // 中等
    [
        'question' => 'What is the main ingredient in guacamole?',
        'option_a' => 'Tomato',
        'option_b' => 'Avocado',
        'option_c' => 'Onion',
        'option_d' => 'Pepper',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'food',
    ],
    [
        'question' => 'What is the largest planet in our solar system?',
        'option_a' => 'Earth',
        'option_b' => 'Mars',
        'option_c' => 'Jupiter',
        'option_d' => 'Saturn',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'science',
    ],
    [
        'question' => 'Which instrument has black and white keys?',
        'option_a' => 'Guitar',
        'option_b' => 'Piano',
        'option_c' => 'Drum',
        'option_d' => 'Flute',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'music',
    ],
    [
        'question' => 'What is the boiling point of water?',
        'option_a' => '100 degrees Celsius',
        'option_b' => '90 degrees Celsius',
        'option_c' => '80 degrees Celsius',
        'option_d' => '70 degrees Celsius',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'medium',
        'category' => 'science',
    ],
    [
        'question' => 'What is the main language spoken in Spain?',
        'option_a' => 'French',
        'option_b' => 'Italian',
        'option_c' => 'Spanish',
        'option_d' => 'Portuguese',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'language',
    ],

    // 困難
    [
        'question' => 'What is the chemical symbol for gold?',
        'option_a' => 'Au',
        'option_b' => 'Ag',
        'option_c' => 'Fe',
        'option_d' => 'Pb',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'hard',
        'category' => 'science',
    ],
    [
        'question' => 'Who wrote the play "Romeo and Juliet"?',
        'option_a' => 'Charles Dickens',
        'option_b' => 'William Shakespeare',
        'option_c' => 'Mark Twain',
        'option_d' => 'J.K. Rowling',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'hard',
        'category' => 'literature',
    ],
    [
        'question' => 'What is the process of converting liquid into vapor called?',
        'option_a' => 'Condensation',
        'option_b' => 'Evaporation',
        'option_c' => 'Precipitation',
        'option_d' => 'Sublimation',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'hard',
        'category' => 'science',
    ],
    [
        'question' => 'Which country is known as the Land of the Rising Sun?',
        'option_a' => 'China',
        'option_b' => 'Japan',
        'option_c' => 'South Korea',
        'option_d' => 'Thailand',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'hard',
        'category' => 'geography',
    ],
    [
        'question' => 'What is the capital of Japan?',
        'option_a' => 'Tokyo',
        'option_b' => 'Kyoto',
        'option_c' => 'Osaka',
        'option_d' => 'Hiroshima',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'hard',
        'category' => 'geography',
    ],

    // 超難
    [
        'question' => 'What is the primary purpose of a business plan?',
        'option_a' => 'To outline goals',
        'option_b' => 'To secure funding',
        'option_c' => 'To analyze competition',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'What does SWOT analysis stand for?',
        'option_a' => 'Strengths, Weaknesses, Opportunities, Threats',
        'option_b' => 'Sales, Wages, Operations, Technology',
        'option_c' => 'Systems, Workflow, Organization, Tracking',
        'option_d' => 'Structure, Workforce, Objectives, Timing',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'What is the significance of cash flow in a business?',
        'option_a' => 'It shows profitability',
        'option_b' => 'It indicates liquidity',
        'option_c' => 'It reflects expenses',
        'option_d' => 'It measures revenue',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'very hard',
        'category' => 'finance',
    ],
    [
        'question' => 'How can effective leadership influence employee morale?',
        'option_a' => 'By fostering a positive work environment',
        'option_b' => 'By implementing strict rules',
        'option_c' => 'By avoiding communication',
        'option_d' => 'By micromanaging',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'very hard',
        'category' => 'management',
    ],
    [
        'question' => 'What is the role of marketing in a business?',
        'option_a' => 'To attract customers',
        'option_b' => 'To enhance product quality',
        'option_c' => 'To reduce costs',
        'option_d' => 'To manage human resources',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'very hard',
        'category' => 'marketing',
    ],
    
    // 混合難度
    [
        'question' => 'What is the primary function of a resume?',
        'option_a' => 'To list references',
        'option_b' => 'To showcase skills and experience',
        'option_c' => 'To provide salary expectations',
        'option_d' => 'To highlight education',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'career',
    ],
    [
        'question' => 'What is the most effective way to manage time?',
        'option_a' => 'Avoiding deadlines',
        'option_b' => 'Prioritizing tasks',
        'option_c' => 'Working overtime',
        'option_d' => 'Multitasking',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'productivity',
    ],
    [
        'question' => 'Which of the following is a benefit of networking?',
        'option_a' => 'Building relationships',
        'option_b' => 'Gaining insights',
        'option_c' => 'Finding job opportunities',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'networking',
    ],
    [
        'question' => 'What is the key element of a successful team?',
        'option_a' => 'Diversity of skills',
        'option_b' => 'Strong leadership',
        'option_c' => 'Open communication',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'teamwork',
    ],
    [
        'question' => 'What is a common reason for employee turnover?',
        'option_a' => 'Job satisfaction',
        'option_b' => 'Competitive salaries',
        'option_c' => 'Lack of advancement opportunities',
        'option_d' => 'Positive workplace culture',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'human resources',
    ],





    // 簡單
    [
        'question' => 'What is your favorite fruit?',
        'option_a' => 'Apple',
        'option_b' => 'Banana',
        'option_c' => 'Cherry',
        'option_d' => 'Grape',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],
    [
        'question' => 'Where do you live?',
        'option_a' => 'In the city',
        'option_b' => 'In the countryside',
        'option_c' => 'In an apartment',
        'option_d' => 'In a house',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'location',
    ],
    [
        'question' => 'What is your favorite hobby?',
        'option_a' => 'Reading',
        'option_b' => 'Traveling',
        'option_c' => 'Cooking',
        'option_d' => 'Gardening',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],
    [
        'question' => 'What type of music do you like?',
        'option_a' => 'Pop',
        'option_b' => 'Rock',
        'option_c' => 'Jazz',
        'option_d' => 'Classical',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'easy',
        'category' => 'music',
    ],
    [
        'question' => 'How do you get to work?',
        'option_a' => 'By car',
        'option_b' => 'By bus',
        'option_c' => 'By bike',
        'option_d' => 'On foot',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'transportation',
    ],

    // 中等
    [
        'question' => 'What are the main features of the new software?',
        'option_a' => 'User-friendly interface',
        'option_b' => 'Advanced security',
        'option_c' => 'Customizable settings',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'technology',
    ],
    [
        'question' => 'How do you handle stress at work?',
        'option_a' => 'Taking breaks',
        'option_b' => 'Exercising',
        'option_c' => 'Talking to someone',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'work',
    ],
    [
        'question' => 'What are your career goals?',
        'option_a' => 'To become a manager',
        'option_b' => 'To learn new skills',
        'option_c' => 'To change industries',
        'option_d' => 'To start a business',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'career',
    ],
    [
        'question' => 'What is the most effective way to study?',
        'option_a' => 'Group study',
        'option_b' => 'Solo study',
        'option_c' => 'Using flashcards',
        'option_d' => 'Taking notes',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'medium',
        'category' => 'education',
    ],
    [
        'question' => 'How can we increase sales this quarter?',
        'option_a' => 'By launching a new marketing campaign',
        'option_b' => 'By improving customer service',
        'option_c' => 'By offering discounts',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],

    // 困難
    [
        'question' => 'What strategies can improve team performance?',
        'option_a' => 'Clear communication',
        'option_b' => 'Defined roles and responsibilities',
        'option_c' => 'Regular feedback',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'teamwork',
    ],
    [
        'question' => 'What are the challenges of remote work?',
        'option_a' => 'Isolation',
        'option_b' => 'Distractions at home',
        'option_c' => 'Communication issues',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'work',
    ],
    [
        'question' => 'How does technology impact our daily lives?',
        'option_a' => 'Increases efficiency',
        'option_b' => 'Enhances communication',
        'option_c' => 'Creates distractions',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'technology',
    ],
    [
        'question' => 'What factors lead to successful project management?',
        'option_a' => 'Proper planning',
        'option_b' => 'Team collaboration',
        'option_c' => 'Adaptability',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'project management',
    ],
    [
        'question' => 'How can we reduce environmental impact?',
        'option_a' => 'By recycling',
        'option_b' => 'By using renewable energy',
        'option_c' => 'By reducing waste',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'environment',
    ],

    // 超難
    [
        'question' => 'What are the implications of artificial intelligence?',
        'option_a' => 'Job displacement',
        'option_b' => 'Ethical concerns',
        'option_c' => 'Enhanced efficiency',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],
    [
        'question' => 'How do cultural differences impact business negotiations?',
        'option_a' => 'Communication styles',
        'option_b' => 'Decision-making processes',
        'option_c' => 'Negotiation tactics',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'What measures can ensure data privacy?',
        'option_a' => 'Encryption',
        'option_b' => 'Regular audits',
        'option_c' => 'Employee training',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],
    [
        'question' => 'How can effective leadership influence an organization?',
        'option_a' => 'Motivating employees',
        'option_b' => 'Creating a positive culture',
        'option_c' => 'Driving innovation',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'leadership',
    ],
    [
        'question' => 'What are the benefits of diversity in the workplace?',
        'option_a' => 'Increased creativity',
        'option_b' => 'Better problem-solving',
        'option_c' => 'Enhanced performance',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'workplace',
    ],




    // 簡單
    [
        'question' => 'What is the main ingredient in a salad?',
        'option_a' => 'Lettuce',
        'option_b' => 'Tomato',
        'option_c' => 'Cucumber',
        'option_d' => 'Carrot',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'food',
    ],
    [
        'question' => 'What time is lunch usually served?',
        'option_a' => '12 PM',
        'option_b' => '1 PM',
        'option_c' => '2 PM',
        'option_d' => '3 PM',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'meal',
    ],
    [
        'question' => 'What color is a ripe banana?',
        'option_a' => 'Green',
        'option_b' => 'Yellow',
        'option_c' => 'Red',
        'option_d' => 'Brown',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'fruit',
    ],
    [
        'question' => 'Where can you find the library?',
        'option_a' => 'In the park',
        'option_b' => 'Next to the school',
        'option_c' => 'In the shopping mall',
        'option_d' => 'At the community center',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'location',
    ],
    [
        'question' => 'How many days are in a week?',
        'option_a' => '5',
        'option_b' => '6',
        'option_c' => '7',
        'option_d' => '8',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'general knowledge',
    ],

    // 中等
    [
        'question' => 'What is the capital of France?',
        'option_a' => 'Berlin',
        'option_b' => 'Madrid',
        'option_c' => 'Paris',
        'option_d' => 'Rome',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'geography',
    ],
    [
        'question' => 'What is the main purpose of advertising?',
        'option_a' => 'To entertain',
        'option_b' => 'To inform',
        'option_c' => 'To persuade',
        'option_d' => 'To educate',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],
    [
        'question' => 'How can employees improve their performance?',
        'option_a' => 'By working longer hours',
        'option_b' => 'By taking regular breaks',
        'option_c' => 'By avoiding teamwork',
        'option_d' => 'By limiting communication',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'work',
    ],
    [
        'question' => 'What is the best way to resolve conflicts at work?',
        'option_a' => 'Ignoring the issue',
        'option_b' => 'Open communication',
        'option_c' => 'Seeking a manager’s help',
        'option_d' => 'Avoiding the person',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'medium',
        'category' => 'communication',
    ],
    [
        'question' => 'Why is teamwork important?',
        'option_a' => 'It saves time',
        'option_b' => 'It enhances creativity',
        'option_c' => 'It leads to better results',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'teamwork',
    ],

    // 困難
    [
        'question' => 'What is the impact of technology on society?',
        'option_a' => 'Improved communication',
        'option_b' => 'Increased efficiency',
        'option_c' => 'Loss of jobs',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'technology',
    ],
    [
        'question' => 'What are the risks of not having a backup plan?',
        'option_a' => 'Data loss',
        'option_b' => 'Increased costs',
        'option_c' => 'Lost time',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'business',
    ],
    [
        'question' => 'How does climate change affect agriculture?',
        'option_a' => 'Decreased crop yields',
        'option_b' => 'Increased pest infestations',
        'option_c' => 'More extreme weather events',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'environment',
    ],
    [
        'question' => 'What are the benefits of renewable energy?',
        'option_a' => 'Sustainable and clean',
        'option_b' => 'Reduces pollution',
        'option_c' => 'Lower long-term costs',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'energy',
    ],
    [
        'question' => 'What strategies can companies use to improve customer satisfaction?',
        'option_a' => 'Personalized services',
        'option_b' => 'Prompt responses',
        'option_c' => 'Regular feedback',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'customer service',
    ],
    
    // 超難
    [
        'question' => 'How does globalization affect local cultures?',
        'option_a' => 'Cultural exchange',
        'option_b' => 'Loss of traditions',
        'option_c' => 'Increased diversity',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'culture',
    ],
    [
        'question' => 'What are the implications of artificial intelligence on the job market?',
        'option_a' => 'Job displacement',
        'option_b' => 'New job creation',
        'option_c' => 'Skill requirements',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],
    [
        'question' => 'How can companies ensure ethical practices?',
        'option_a' => 'Transparent policies',
        'option_b' => 'Regular audits',
        'option_c' => 'Employee training',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'business ethics',
    ],
    [
        'question' => 'What role does social media play in modern marketing?',
        'option_a' => 'Increased reach',
        'option_b' => 'Direct customer engagement',
        'option_c' => 'Brand awareness',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'marketing',
    ],
    [
        'question' => 'What are the consequences of poor financial planning?',
        'option_a' => 'Debt accumulation',
        'option_b' => 'Limited growth opportunities',
        'option_c' => 'Financial instability',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'finance',
    ],
    [
        'question' => 'How do trade agreements benefit countries?',
        'option_a' => 'Increased trade',
        'option_b' => 'Economic growth',
        'option_c' => 'Job creation',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'economics',
    ],
    [
        'question' => 'What factors contribute to successful change management?',
        'option_a' => 'Clear communication',
        'option_b' => 'Employee involvement',
        'option_c' => 'Proper training',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'management',
    ],
    [
        'question' => 'What is the significance of emotional intelligence in leadership?',
        'option_a' => 'Better team collaboration',
        'option_b' => 'Improved decision-making',
        'option_c' => 'Effective conflict resolution',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'leadership',
    ],
    [
        'question' => 'What are the challenges of implementing new technology in the workplace?',
        'option_a' => 'Resistance to change',
        'option_b' => 'Training requirements',
        'option_c' => 'Integration with existing systems',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],
    [
        'question' => 'How can effective negotiation skills benefit a business?',
        'option_a' => 'Better contracts',
        'option_b' => 'Stronger partnerships',
        'option_c' => 'Increased profitability',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'negotiation',
    ],



    // 簡單
    [
        'question' => 'What is your favorite food?',
        'option_a' => 'Pizza',
        'option_b' => 'Sushi',
        'option_c' => 'Pasta',
        'option_d' => 'Salad',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'personal',
    ],
    [
        'question' => 'What color is the sky?',
        'option_a' => 'Blue',
        'option_b' => 'Green',
        'option_c' => 'Red',
        'option_d' => 'Yellow',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'nature',
    ],
    [
        'question' => 'How do you get to school?',
        'option_a' => 'By bus',
        'option_b' => 'By car',
        'option_c' => 'By bike',
        'option_d' => 'Walking',
        'correct_answer' => 'option_a',
        'difficulty_level' => 'easy',
        'category' => 'transportation',
    ],
    [
        'question' => 'What time is breakfast served?',
        'option_a' => '7 AM',
        'option_b' => '8 AM',
        'option_c' => '9 AM',
        'option_d' => '10 AM',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'easy',
        'category' => 'food',
    ],
    [
        'question' => 'How many days are there in a week?',
        'option_a' => '5',
        'option_b' => '6',
        'option_c' => '7',
        'option_d' => '8',
        'correct_answer' => 'option_c',
        'difficulty_level' => 'easy',
        'category' => 'general knowledge',
    ],

    // 中等
    [
        'question' => 'What are the advantages of public transportation?',
        'option_a' => 'Cost-effective',
        'option_b' => 'Environmentally friendly',
        'option_c' => 'Reduces traffic',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'transportation',
    ],
    [
        'question' => 'What is the main goal of a business plan?',
        'option_a' => 'To secure funding',
        'option_b' => 'To outline the company’s vision',
        'option_c' => 'To analyze the competition',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'business',
    ],
    [
        'question' => 'How can we reduce waste in the office?',
        'option_a' => 'By recycling',
        'option_b' => 'By using digital documents',
        'option_c' => 'By minimizing printing',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'environment',
    ],
    [
        'question' => 'What is the purpose of a marketing strategy?',
        'option_a' => 'To increase sales',
        'option_b' => 'To understand the market',
        'option_c' => 'To define target customers',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'marketing',
    ],
    [
        'question' => 'What is a common symptom of stress?',
        'option_a' => 'Headaches',
        'option_b' => 'Fatigue',
        'option_c' => 'Irritability',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'medium',
        'category' => 'health',
    ],

    // 困難
    [
        'question' => 'What is the importance of networking in business?',
        'option_a' => 'Building relationships',
        'option_b' => 'Finding new opportunities',
        'option_c' => 'Sharing knowledge',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'business',
    ],
    [
        'question' => 'How can effective leadership impact a team?',
        'option_a' => 'Improved morale',
        'option_b' => 'Increased productivity',
        'option_c' => 'Better communication',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'leadership',
    ],
    [
        'question' => 'What are the challenges of remote work?',
        'option_a' => 'Isolation',
        'option_b' => 'Distractions',
        'option_c' => 'Communication issues',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'work',
    ],
    [
        'question' => 'How do you measure the success of a marketing campaign?',
        'option_a' => 'Sales increase',
        'option_b' => 'Customer feedback',
        'option_c' => 'Website traffic',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'marketing',
    ],
    [
        'question' => 'What is the role of a project manager?',
        'option_a' => 'To oversee the project',
        'option_b' => 'To manage the team',
        'option_c' => 'To allocate resources',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'hard',
        'category' => 'management',
    ],

    // 超難
    [
        'question' => 'What are the key elements of a successful negotiation?',
        'option_a' => 'Preparation',
        'option_b' => 'Clear communication',
        'option_c' => 'Flexibility',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'negotiation',
    ],
    [
        'question' => 'How can you effectively handle conflict in the workplace?',
        'option_a' => 'Avoid it',
        'option_b' => 'Address it directly',
        'option_c' => 'Seek mediation',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_b',
        'difficulty_level' => 'very hard',
        'category' => 'conflict resolution',
    ],
    [
        'question' => 'What is the significance of emotional intelligence in leadership?',
        'option_a' => 'Improves team dynamics',
        'option_b' => 'Enhances decision-making',
        'option_c' => 'Increases empathy',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'leadership',
    ],
    [
        'question' => 'How does globalization impact local businesses?',
        'option_a' => 'Increased competition',
        'option_b' => 'Access to new markets',
        'option_c' => 'Cultural exchange',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'business',
    ],
    [
        'question' => 'What strategies can enhance team collaboration?',
        'option_a' => 'Regular meetings',
        'option_b' => 'Team-building activities',
        'option_c' => 'Clear goals',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'teamwork',
    ],
    [
        'question' => 'What factors contribute to effective time management?',
        'option_a' => 'Prioritization',
        'option_b' => 'Goal setting',
        'option_c' => 'Scheduling',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'time management',
    ],
    [
        'question' => 'What is the role of corporate social responsibility?',
        'option_a' => 'Enhancing brand image',
        'option_b' => 'Promoting ethical practices',
        'option_c' => 'Supporting community initiatives',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'corporate responsibility',
    ],
    [
        'question' => 'What challenges do startups face in their early stages?',
        'option_a' => 'Funding',
        'option_b' => 'Market competition',
        'option_c' => 'Building a customer base',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'entrepreneurship',
    ],
    [
        'question' => 'What are the implications of artificial intelligence in the workplace?',
        'option_a' => 'Job displacement',
        'option_b' => 'Increased efficiency',
        'option_c' => 'Ethical concerns',
        'option_d' => 'All of the above',
        'correct_answer' => 'option_d',
        'difficulty_level' => 'very hard',
        'category' => 'technology',
    ],


        ];

        foreach ($questions as $index => $question) {
            // 使用服務生成音頻
            $audioFile = $ttsService->generateAudio($question['question'], [
                'option_a' => $question['option_a'],
                'option_b' => $question['option_b'],
                'option_c' => $question['option_c'],
                'option_d' => $question['option_d'],
            ], 'question_' . ($index + 1));
        
            // 將問題和音頻文件插入資料庫
            ListeningQuestion::create([
                'question' => $question['question'],
                'option_a' => $question['option_a'],
                'option_b' => $question['option_b'],
                'option_c' => $question['option_c'],
                'option_d' => $question['option_d'],
                'correct_answer' => $question['correct_answer'],
                'difficulty_level' => $question['difficulty_level'],
                'category' => $question['category'],
                'audio_file' => $audioFile, // 保存音頻文件路徑
            ]);
        }
        
    }
}
